# Generated by Django 6.0.7 on 2026-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fardo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('safra', models.CharField(max_length=9)),
                ('produtor', models.CharField(max_length=120)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_classificacao', models.DateField()),
            ],
        ),
    ]
