# Generated by Django 6.0.7 on 2026-09-09 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('season', models.CharField(max_length=9)),
                ('producer', models.CharField(max_length=120)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('classification_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=120)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('closing_date', models.DateField(auto_now_add=True)),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='desk.bale')),
            ],
        ),
        migrations.CreateModel(
            name='HVIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micronaire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('strength', models.DecimalField(decimal_places=1, max_digits=4)),
                ('uniformity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='desk.bale')),
            ],
        ),
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trading_date', models.DateField()),
            ],
            options={
                'unique_together': {('code', 'trading_date')},
            },
        ),
    ]
