# Generated by Django 6.0.7 on 2026-07-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoHVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micronaire', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resistencia', models.DecimalField(decimal_places=1, max_digits=4)),
                ('uniformidade', models.DecimalField(decimal_places=1, max_digits=4)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('fardo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='desk.fardo')),
            ],
        ),
    ]
