# Generated by Django 6.0.7 on 2026-07-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_laudohvi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=120)),
                ('preco_por_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_fechamento', models.DateField(auto_now_add=True)),
                ('fardo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='desk.fardo')),
            ],
        ),
    ]
