# Generated by Django 6.0.7 on 2026-07-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicePreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pregao', models.DateField()),
            ],
            options={
                'unique_together': {('codigo', 'data_pregao')},
            },
        ),
    ]
